[package]
name = "ws"
version = "0.2.0"
authors = ["deebloo <dannybluedesign@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.32.0", features = ["full"] }
ws_core = { path = "packages/core" }
ws_rtl_433 = { path = "packages/rtl_433" }
ws_display = { path = "packages/display" }
ws_influxdb = { path = "packages/influxdb" }
dotenv = "0.15.0"
metrum = { version = "0.2.0", features = ["serde"]}

[dev-dependencies]
async-trait = "0.1.73"

[workspace]
members = [
    "packages/*",
]
