[package]
name = "acurite"
version = "0.2.0"
authors = ["dblue <dblue@deloitte.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.15.0", features = ["full"] }
async-trait = "0.1.52"
chrono = "0.4.19"
hidapi = "1.3.0"
influxdb = { version = "0.5.0", features = ["derive"] }
serde = "1.0.131"
serde_json = "1.0.73"
acurite_core = { path = "core" }
