[package]
name = "acurite"
version = "0.2.0"
authors = ["dblue <dblue@deloitte.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.29.1", features = ["full"] }
async-trait = "0.1.71"
chrono = "0.4.26"
serde = "1.0.175"
serde_json = "1.0.103"
acurite_core = { path = "packages/core" }
acurite_console = { path = "packages/console" }
acurite_rtl_433 = { path = "packages/rtl_433" }
acurite_influx = { path = "packages/influx" }

[workspace]
members = [
    "packages/*",
]