[package]
name = "weather_station"
version = "0.2.0"
authors = ["deebloo <dannybluedesign@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.29.1", features = ["full"] }
weather = { path = "packages/weather" }
rtl_433 = { path = "packages/rtl_433" }
display = { path = "packages/display" }
influx_db = { path = "packages/influx_db" }

[dev-dependencies]
async-trait = "0.1.73"

[workspace]
members = [
    "packages/*",
]