version: "3.9"

services:
  # weather:
  #   container_name: weather
  #   build: .
  #   privileged: true
  #   environment:
  #     - WEATHER_SOURCE=RTL433
  #     - WEATHER_INFLUXDB_URL=http://influxdb:8086
  #     - WEATHER_INFLUXDB_DB=weather
  #   volumes:
  #     - /dev/bus/usb:/dev/bus/usb
  #   depends_on:
  #     - influxdb
  #     - grafana

  influxdb:
    container_name: influxdb
    image: influxdb:1.8.10
    restart: always
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=weather
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise:10.0.3
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data:
