version: "3.9"

services:
  # influxdb2:
  #   container_name: influxdb2
  #   image: influxdb:2.7.1
  #   restart: always
  #   ports:
  #     - 8087:8086
    # environment:
      # DOCKER_INFLUXDB_INIT_MODE=upgrade
      # DOCKER_INFLUXDB_INIT_USERNAME=my-user
      # DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      # DOCKER_INFLUXDB_INIT_ORG=my-org
      # DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
    # volumes:
    #   - influxdb2_data:/var/lib/influxdb2

  influxdb:
    image: influxdb:1.8.10
    restart: always
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=weather
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana-oss:10.0.3
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  # influxdb2_data:
  grafana_data:
