version: "3.9"

services:
  influxdb:
    container_name: influxdb
    image: influxdb:1.8.9
    restart: always
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=weather
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    container_name: grafana
    image: grafana/grafana:8.1.3
    restart: always
    environment:
      - GF_SERVER_DOMAIN=0.0.0.0
      - GF_SERVER_ROOT_URL=http://0.0.0.0/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

  nginx:
    container_name: nginx
    image: nginx:1.21.1
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - grafana

volumes:
  influxdb_data:
  grafana_data:
