[package]
name = "ws_influx_db"
version = "0.2.0"
authors = ["deebloo <dannybluedesign@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.73"
chrono = "0.4.28"
serde = "1.0.188"
serde_json = "1.0.105"
reqwest = { version = "0.11", features = ["json"] }
ws_core = { path = "../core" }