[package]
name = "influx_db"
version = "0.2.0"
authors = ["dblue <dblue@deloitte.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.73"
chrono = "0.4.26"
influxdb = { version = "0.7.0", features = ["derive"] }
serde = "1.0.181"
serde_json = "1.0.104"
weather = { path = "../weather" }