[package]
name = "acurite_rtl_433"
version = "0.2.0"
authors = ["dblue <dblue@deloitte.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
serde = "1.0.159"
serde_json = "1.0.93"
acurite_core = { path = "../core" }