[package]
name = "ws_rtl_433"
version = "0.2.0"
authors = ["deebloo <dannybluedesign@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.73"
chrono = "0.4.31"
serde = "1.0.188"
serde_json = "1.0.107"
degrees = { version = "0.6.0", features = ["serde"] }
ws_core = { path = "../core" }