[package]
name = "ws_core"
version = "0.2.0"
authors = ["deebloo <dannybluedesign@gmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.73"
chrono = { version = "0.4.28", features = ["serde"]}
serde = { version = "1.0.188", features = ["derive"]}
serde_json = "1.0.105"