[package]
name = "acurite_core"
version = "0.2.0"
authors = ["dblue <dblue@deloitte.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }
async-trait = "0.1.64"
chrono = "0.4.24"
hidapi = "1.5.0"
serde = "1.0.152"
serde_json = "1.0.93"