[package]
name = "acurite_console"
version = "0.2.0"
authors = ["dblue <dblue@deloitte.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.20.1", features = ["full"] }
chrono = "0.4.22"
serde = "1.0.144"
serde_json = "1.0.82"
acurite_core = { path = "../core" }