[package]
name = "acurite_console"
version = "0.2.0"
authors = ["dblue <dblue@deloitte.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.14.0", features = ["full"] }
hidapi = "1.3.0"
chrono = "0.4.19"
serde = "1.0.132"
serde_json = "1.0.72"
acurite_core = { path = "../core" }