[package]
name = "acurite_influx"
version = "0.2.0"
authors = ["dblue <dblue@deloitte.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.71"
chrono = "0.4.26"
influxdb = { version = "0.7.0", features = ["derive"] }
serde = "1.0.169"
serde_json = "1.0.100"
acurite_core = { path = "../core" }