[package]
name = "acurite_influx"
version = "0.2.0"
authors = ["dblue <dblue@deloitte.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.59"
chrono = "0.4.23"
influxdb = { version = "0.5.2", features = ["derive"] }
serde = "1.0.148"
serde_json = "1.0.89"
acurite_core = { path = "../core" }